export const ROUTES = {
  home: '/',
  catalog: '/catalog',
  tutor: (slug: string) => `/tutor/${slug}`,
  forStudents: '/for-students',
  forTutors: '/for-tutors',
  support: '/support',
  blog: '/blog',
  about: '/about',
  contacts: '/contacts',
  becomeTutor: '/become-tutor',
  becomeTutorRegister: '/become-tutor/register',
  becomeTutorSuccess: '/become-tutor/success',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  cabinet: '/cabinet',
  cabinetProfile: '/cabinet/profile',
  cabinetAnalytics: '/cabinet/analytics',
  legal: {
    offer: '/legal/tutor-offer',
    privacy: '/legal/privacy',
    cookie: '/legal/cookies',
    rules: '/legal/rules',
  },
} as const;
